project:
  type: website

website:
  title: "301L_Course-Site"
  navbar:
    background: primary
    search: false
    left:
      - href: index.qmd
        text: Home
      - text: Lab Contents
        menu:
        - href: drosophila-evolution.qmd
        - href: distributions.qmd
      - text: Lab Reports
        menu:
        - href: citations.qmd
      - text: Statistics & Data Analysis
        menu:
        - href: p-values.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



